apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: hyperpage-ingress
  labels:
    app: hyperpage
  annotations:
    # Enable SSL/TLS termination
    cert-manager.io/cluster-issuer: "letsencrypt-prod"
    # Rate limiting
    nginx.ingress.kubernetes.io/rate-limit: "100"
    nginx.ingress.kubernetes.io/rate-limit-window: "1m"
    # Security headers
    nginx.ingress.kubernetes.io/configuration-snippet: |
      add_header X-Frame-Options DENY always;
      add_header X-Content-Type-Options nosniff always;
      add_header X-XSS-Protection "1; mode=block" always;
      add_header Referrer-Policy "strict-origin-when-cross-origin" always;
    # Enable CORS
    nginx.ingress.kubernetes.io/enable-cors: "true"
    nginx.ingress.kubernetes.io/cors-allow-origin: "https://your-domain.com"
    nginx.ingress.kubernetes.io/cors-allow-methods: "GET, POST, PUT, DELETE, OPTIONS"
    nginx.ingress.kubernetes.io/cors-allow-headers: "DNT,Keep-Alive,User-Agent,X-Requested-With,If-Modified-Since,Cache-Control,Content-Type,Range,Authorization"
spec:
  ingressClassName: nginx  # Adjust based on your ingress controller

  # TLS configuration
  tls:
  - hosts:
    - your-domain.com
    - api.your-domain.com
    secretName: hyperpage-tls

  rules:
  # Main application
  - host: your-domain.com
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: hyperpage-service
            port:
              number: 80

  # API endpoints (optional separate host)
  - host: api.your-domain.com
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: hyperpage-service
            port:
              number: 80
---
# NetworkPolicy for secure communication
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: hyperpage-network-policy
  labels:
    app: hyperpage
spec:
  podSelector:
    matchLabels:
      app: hyperpage
  policyTypes:
  - Ingress
  - Egress

  # Ingress rules
  ingress:
  # Allow traffic from ingress controller
  - from:
    - namespaceSelector:
        matchLabels:
          name: ingress-nginx
    ports:
    - protocol: TCP
      port: 3000

  # Allow traffic from other hyperpage pods (for internal communication)
  - from:
    - podSelector:
        matchLabels:
          app: hyperpage
    ports:
    - protocol: TCP
      port: 3000

  # Egress rules
  egress:
  # Allow DNS resolution
  - to: []
    ports:
    - protocol: UDP
      port: 53

  # Allow HTTP/HTTPS to external APIs
  - to: []
    ports:
    - protocol: TCP
      port: 80
    - protocol: TCP
      port: 443

  # Allow traffic to kube-system (for DNS, etc.)
  - to:
    - namespaceSelector:
        matchLabels:
          name: kube-system

  # Allow traffic within cluster
  - to:
    - podSelector: {}
